from django.urls import path

from commerce import views

urlpatterns = [
    path("", views.public_page, {"page": "index.html"}),
    path("<str:page>.html", views.public_page),
    path("api/session", views.api_session),
    path("api/login", views.api_login),
    path("api/logout", views.api_logout),
    path("api/products", views.api_products),
    path("api/cep/<str:cep>", views.api_cep),
    path("api/shipping/quote", views.api_shipping_quote),
    path("api/coupons/validate", views.api_coupons_validate),
    path("api/checkout", views.api_checkout),
    path("api/customer/access", views.api_customer_access),
    path("api/customer/orders", views.api_customer_orders),
    path("api/custom-requests", views.api_custom_requests),
    path("api/custom-requests/<str:request_id>/messages", views.api_custom_request_messages),
    path("api/admin/dashboard", views.api_admin_dashboard),
    path("api/admin/settings", views.api_admin_settings),
    path("api/admin/hero-slides", views.api_admin_hero_slides),
    path("api/admin/hero-slides/<str:slide_id>", views.api_admin_hero_slide_detail),
    path("api/admin/coupons", views.api_admin_coupons),
    path("api/admin/stories", views.api_admin_stories),
    path("api/admin/stories/<str:story_id>", views.api_admin_story_detail),
    path("api/admin/customers", views.api_admin_customers),
    path("api/admin/customers/<str:customer_id>", views.api_admin_customer_detail),
    path("api/admin/affiliates", views.api_admin_affiliates),
    path("api/admin/affiliates/<str:affiliate_id>", views.api_admin_affiliate_detail),
    path("api/admin/sellers", views.api_admin_sellers),
    path("api/admin/sellers/<str:seller_id>", views.api_admin_seller_detail),
    path("api/admin/orders/<str:order_id>", views.api_admin_order_detail),
    path("api/admin/custom-requests/<str:request_id>", views.api_admin_custom_request_detail),
    path("api/admin/products", views.api_admin_products),
    path("api/admin/products/<str:product_id>/campaign", views.api_admin_product_campaign),
    path("api/admin/products/<str:product_id>", views.api_admin_product_detail),
]
